name: Proposal Management

on:
  issues:
    types: [opened, labeled]

jobs:
  new-proposal:
    if: contains(github.event.issue.labels.*.name, 'proposal')
    runs-on: ubuntu-latest
    steps:
      - name: Add welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🎉 Thank you for your proposal submission!
              
              **Proposal #${context.issue.number}** has been received and will be reviewed by our data science team.
              
              ### What happens next:
              1. **Initial Review** (1-2 business days) - We'll check your proposal for completeness
              2. **Data Availability Check** (2-3 business days) - We'll verify required data exists  
              3. **Team Assignment** - A data scientist will be assigned to your project
              4. **Project Planning** - We'll create a timeline and contact you to discuss next steps
              
              ### Your Reference Number: **#${context.issue.number}**
              
              Please use this number in all future communications about this proposal.
              
              If you have urgent questions, contact us at: icu-datahub@ukmuenster.de
              
              Thank you for choosing our ICU Data Hub for your research!
              
              *— ICU Data Science Team*`
            })

      - name: Assign to team
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ['your-github-username'] // Replace with actual usernames
            })

      - name: Add project board
        uses: actions/github-script@v7
        with:
          script: |
            // Optional: Add to project board for tracking
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['under-review', 'needs-triage']
            })